import unittest
from jarvis_completion_validator.reviewer import Reviewer
from jarvis_completion_validator.recommendations import determine_recommendation
from jarvis_completion_validator.enums import Recommendation
from tests.helpers import merge_task_and_result

class TestRecommendations(unittest.TestCase):
    def test_accept(self):
        raw_data = merge_task_and_result("task-envelope-example", "valid-complete-result", "valid-complete-artifacts")
        # Remove manual review for auto accept
        raw_data["task"]["completion_criteria"] = [c for c in raw_data["task"]["completion_criteria"] if not c.get("human_review_required")]
        reviewer = Reviewer(raw_data)
        res = reviewer.review()
        rec, _ = determine_recommendation(res["task_data"], res["evaluated_criteria"], res["findings"])
        self.assertEqual(rec.recommendation, Recommendation.ACCEPT)

    def test_accept_with_warnings(self):
        raw_data = merge_task_and_result("task-envelope-example", "valid-complete-result", "valid-complete-artifacts")
        raw_data["task"]["completion_criteria"] = [c for c in raw_data["task"]["completion_criteria"] if not c.get("human_review_required")]
        raw_data["worker_result"]["warnings"] = ["A minor warning"]
        reviewer = Reviewer(raw_data)
        res = reviewer.review()
        rec, _ = determine_recommendation(res["task_data"], res["evaluated_criteria"], res["findings"])
        self.assertEqual(rec.recommendation, Recommendation.ACCEPT_WITH_WARNINGS)

    def test_request_revision(self):
        raw_data = merge_task_and_result("task-envelope-example", "incomplete-result")
        raw_data["task"]["completion_criteria"] = [c for c in raw_data["task"]["completion_criteria"] if not c.get("human_review_required")]
        reviewer = Reviewer(raw_data)
        res = reviewer.review()
        rec, _ = determine_recommendation(res["task_data"], res["evaluated_criteria"], res["findings"])
        self.assertEqual(rec.recommendation, Recommendation.REQUEST_REVISION)

    def test_reject_policy(self):
        raw_data = merge_task_and_result("task-envelope-example", "policy-violation-result")
        reviewer = Reviewer(raw_data)
        res = reviewer.review()
        rec, _ = determine_recommendation(res["task_data"], res["evaluated_criteria"], res["findings"])
        self.assertEqual(rec.recommendation, Recommendation.REJECT)

    def test_request_approval(self):
        raw_data = merge_task_and_result("task-envelope-example", "approval-required-result", "valid-complete-artifacts")
        raw_data["task"]["completion_criteria"] = [c for c in raw_data["task"]["completion_criteria"] if not c.get("human_review_required")]
        reviewer = Reviewer(raw_data)
        res = reviewer.review()
        rec, _ = determine_recommendation(res["task_data"], res["evaluated_criteria"], res["findings"])
        self.assertEqual(rec.recommendation, Recommendation.REQUEST_APPROVAL)

    def test_block(self):
        raw_data = merge_task_and_result("task-envelope-example", "blocked-result")
        # In a real impl, blocking findings would be explicitly generated by a dependency check logic.
        # For prototype, we simulate a finding that recommends block.
        reviewer = Reviewer(raw_data)
        res = reviewer.review()
        # Mocking a block recommendation from a finding to test precedence
        from jarvis_completion_validator.contracts import ReviewerFinding
        from jarvis_completion_validator.enums import FindingSeverity, FindingCategory
        res["findings"].append(ReviewerFinding(
            finding_id="mock", severity=FindingSeverity.MAJOR, category=FindingCategory.CRITERION_UNMET,
            summary="blocked", detailed_reason="blocked", automatically_remediable=False, recommended_next_action="block"
        ))
        rec, _ = determine_recommendation(res["task_data"], res["evaluated_criteria"], res["findings"])
        self.assertEqual(rec.recommendation, Recommendation.BLOCK)

    def test_human_review(self):
        raw_data = merge_task_and_result("task-envelope-example", "valid-complete-result", "valid-complete-artifacts")
        # task-envelope-example includes criterion-003 with human_review_required=True
        reviewer = Reviewer(raw_data)
        res = reviewer.review()
        rec, _ = determine_recommendation(res["task_data"], res["evaluated_criteria"], res["findings"])
        self.assertEqual(rec.recommendation, Recommendation.HUMAN_REVIEW)

if __name__ == "__main__":
    unittest.main()
