import { act, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { BrowserRouter } from 'react-router-dom'
import { beforeEach, describe, expect, test, vi } from 'vitest'
import App from '../src/App'
import { AppStoreProvider } from '../src/state/AppStore'
import type { Agent, Approval, Artifact, AuditEvent, Department, Notification, SystemStatus, Task } from '../src/types/contracts'

const now='2026-01-15T14:00:00Z'
const agents:Agent[]=['jarvis','atlas','scout','archive','sentinel'].map((id,index)=>({id,schemaVersion:'1.0',name:id[0]!.toUpperCase()+id.slice(1),role:index===0?'Executive Manager':'Specialist',description:'Simulated agent',goals:['Be transparent'],departmentId:index===0?'executive':'research',managerId:index===0?null:'jarvis',status:'idle',currentTaskId:null,queuedTaskIds:[],progress:0,statusMessage:'Available',capabilities:['simulation'],allowedTools:['fixture'],deniedTools:['shell'],approvalPolicy:{},memoryAccess:{},performance:{completionRate:.9,accuracyScore:.9,averageCompletionTime:10,failedTaskCount:0,userCorrectionCount:0,reviewerScore:.9,reliabilityScore:.95},resourceProfile:{},office:{zone:index===0?'Executive':'Research',deskId:`D-${index}`,spriteIdentifier:id,displayPosition:{x:1,y:1},currentAnimationState:'idle',currentDestination:null,isInMeeting:false},createdAt:now,updatedAt:now,version:'1',deploymentStatus:'simulated',isTemporary:false}))
const tasks:Task[]=[{id:'task-parent',schemaVersion:'1.0',title:'Caribbean recommendation',description:'Fixture trip',request:'Plan a trip',parentTaskId:null,childTaskIds:['task-child'],projectId:null,createdBy:'user',assignedManagerId:'jarvis',assignedAgentIds:['scout'],priority:'high',status:'in_progress',progress:45,statusMessage:'Researching fixtures',dependencies:[],blockedBy:[],approvalIds:['approval-pending'],artifactIds:[],result:null,error:null,retryCount:0,maxRetries:2,createdAt:now,startedAt:now,updatedAt:now,completedAt:null},{id:'task-child',schemaVersion:'1.0',title:'Research destinations',description:'Child',request:'Research',parentTaskId:'task-parent',childTaskIds:[],projectId:null,createdBy:'jarvis',assignedManagerId:'atlas',assignedAgentIds:['scout'],priority:'medium',status:'in_progress',progress:30,statusMessage:'Working',dependencies:[],blockedBy:[],approvalIds:[],artifactIds:[],result:null,error:null,retryCount:0,maxRetries:2,createdAt:now,startedAt:now,updatedAt:now,completedAt:null}]
const approvals:Approval[]=[{id:'approval-pending',taskId:'task-parent',requestedByAgentId:'scout',actionType:'simulated_publish',title:'Publish report',description:'Simulation only',reason:'Review gate',riskLevel:'yellow',affectedResources:['fixture'],exactActionPreview:'Save fixture',expectedOutcome:'Artifact appears',reversalMethod:'Reset',expiresAt:'2035-01-01T00:00:00Z',status:'pending',reviewedBy:null,reviewedAt:null,decisionNote:null,createdAt:now},{id:'approval-expired',taskId:'task-parent',requestedByAgentId:'scout',actionType:'simulated_read',title:'Expired request',description:'Expired simulation',reason:'Test',riskLevel:'orange',affectedResources:['fixture'],exactActionPreview:'None',expectedOutcome:'None',reversalMethod:'None',expiresAt:'2020-01-01T00:00:00Z',status:'expired',reviewedBy:null,reviewedAt:null,decisionNote:null,createdAt:now},{id:'approval-black',taskId:'task-parent',requestedByAgentId:'sentinel',actionType:'prohibited',title:'Prohibited action',description:'Never allowed',reason:'Boundary',riskLevel:'black',affectedResources:['external'],exactActionPreview:'None',expectedOutcome:'Refused',reversalMethod:'None',expiresAt:'2035-01-01T00:00:00Z',status:'pending',reviewedBy:null,reviewedAt:null,decisionNote:null,createdAt:now}]
const departments:Department[]=[{id:'executive',name:'Executive',description:'',managerAgentId:'jarvis',agentIds:['jarvis']},{id:'research',name:'Research and Knowledge',description:'',managerAgentId:'atlas',agentIds:['atlas','scout','archive','sentinel']}]
const auditEvents:AuditEvent[]=[{id:'audit-1',timestamp:now,eventType:'task.created',actorAgentId:'jarvis',taskId:'task-parent',previousState:'queued',newState:'in_progress',summary:'Task entered research',correlationId:'demo',sequenceNumber:1,payload:{simulated:true},artifactIds:[],approvalId:null}]
const notifications:Notification[]=[{id:'n1',title:'Hello',message:'Simulation',level:'info',isRead:false,taskId:null,createdAt:now}]
const artifacts:Artifact[]=[]
const system:SystemStatus={status:'healthy',environment:'test',apiSchemaVersion:'1.0',seedDataVersion:'1.0',emergencyStop:false,simulator:{state:'running',currentStep:4,totalSteps:25,accelerated:true},resources:[{name:'CPU',value:'fixture 18%',label:'Simulated'}],lastSynchronizedAt:now}
const endpointData:Record<string,unknown>={'/api/departments':departments,'/api/agents':agents,'/api/tasks':tasks,'/api/approvals':approvals,'/api/artifacts':artifacts,'/api/audit-events':auditEvents,'/api/notifications':notifications,'/api/system/status':system}

class FakeWebSocket {static instances:FakeWebSocket[]=[];static OPEN=1;readyState=1;onopen:(()=>void)|null=null;onmessage:((event:{data:string})=>void)|null=null;onerror:(()=>void)|null=null;onclose:(()=>void)|null=null;constructor(public url:string){FakeWebSocket.instances.push(this);queueMicrotask(()=>this.onopen?.())}close(){}send(){}emit(event:unknown){this.onmessage?.({data:JSON.stringify(event)})}}

function renderApp(){return render(<BrowserRouter><AppStoreProvider><App/></AppStoreProvider></BrowserRouter>)}
beforeEach(()=>{window.history.pushState({},'', '/');FakeWebSocket.instances=[];vi.stubGlobal('WebSocket',FakeWebSocket);vi.stubGlobal('fetch',vi.fn(async(input:string|URL|Request,init?:RequestInit)=>{const path=new URL(typeof input==='string'?input:input instanceof URL?input.href:input.url).pathname;const data=endpointData[path]??(init?.method==='POST'?{}:[]);return {ok:true,status:200,json:async()=>({data,meta:{schemaVersion:'1.0'}})} as Response}))})

describe('Jarvis interface',()=>{
 test('dashboard renders synchronized seed state',async()=>{renderApp();expect(await screen.findByText('Good evening, operator.')).toBeInTheDocument();expect(screen.getByText('Available agents')).toBeInTheDocument();expect(screen.getByText('fixture 18%')).toBeInTheDocument()})
 test('agent list and shared details render',async()=>{renderApp();await screen.findByText('Good evening, operator.');await userEvent.click(screen.getAllByRole('link',{name:'Agents'})[0]!);expect(await screen.findByText('Five permanent operators')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Open Jarvis'}));expect(screen.getByRole('dialog',{name:'Jarvis'})).toBeInTheDocument();expect(screen.getByText('Tool policy')).toBeInTheDocument()})
 test('task hierarchy renders and opens details',async()=>{renderApp();await screen.findByText('Good evening, operator.');await userEvent.click(screen.getAllByRole('link',{name:'Tasks'})[0]!);expect(await screen.findByText('1 subtasks')).toBeInTheDocument();await userEvent.click(screen.getByRole('button',{name:'Open Caribbean recommendation'}));expect(screen.getByText('Original request')).toBeInTheDocument();expect(screen.getByText('Research destinations')).toBeInTheDocument()})
 test('pending approval renders and policy disables unsafe actions',async()=>{renderApp();await screen.findByText('Good evening, operator.');await userEvent.click(screen.getAllByRole('link',{name:'Approvals'})[0]!);expect(await screen.findByText('Publish report')).toBeInTheDocument();const cards=screen.getAllByRole('article');expect(cards[1]!.querySelector('button')).toBeDisabled();expect(cards[2]!.querySelector('button')).toBeDisabled();expect(screen.getByText(/Black-risk actions are prohibited/)).toBeInTheDocument()})
 test('approval action refreshes UI',async()=>{renderApp();await screen.findByText('Good evening, operator.');await userEvent.click(screen.getAllByRole('link',{name:'Approvals'})[0]!);await userEvent.click(screen.getAllByRole('button',{name:'Approve'})[0]!);await waitFor(()=>expect(screen.getByRole('status')).toHaveTextContent('Approval approved'))})
 test('emergency-stop state is visible in system data',async()=>{endpointData['/api/system/status']={...system,emergencyStop:true,simulator:{...system.simulator,state:'paused'}};renderApp();expect(await screen.findByRole('button',{name:'Resume system'})).toBeInTheDocument();endpointData['/api/system/status']=system})
 test('mobile navigation exists with semantic label',async()=>{renderApp();expect(await screen.findByRole('navigation',{name:'Mobile primary'})).toBeInTheDocument()})
 test('offline browser state is announced',async()=>{renderApp();await screen.findByText('Good evening, operator.');act(()=>window.dispatchEvent(new Event('offline')));expect(screen.getAllByText('offline').length).toBeGreaterThan(0)})
 test('office uses shared agents and opens shared detail',async()=>{renderApp();window.history.pushState({},'','/office');await act(async()=>window.dispatchEvent(new PopStateEvent('popstate')));await userEvent.click(await screen.findByRole('button',{name:/Jarvis/}));expect(screen.getByRole('dialog',{name:'Jarvis'})).toBeInTheDocument()})
 test('duplicate websocket sequence is ignored',async()=>{renderApp();await screen.findByText('Good evening, operator.');const before=vi.mocked(fetch).mock.calls.length;const event={eventId:'e1',schemaVersion:'1',eventType:'noop',timestamp:now,sequenceNumber:2,correlationId:'c',taskId:null,agentId:null,source:'test',payload:{}};act(()=>{FakeWebSocket.instances[0]!.emit(event);FakeWebSocket.instances[0]!.emit(event)});await waitFor(()=>expect(vi.mocked(fetch).mock.calls.length).toBe(before+8))})
 test('out-of-order websocket event triggers HTTP resynchronization',async()=>{renderApp();await screen.findByText('Good evening, operator.');const before=vi.mocked(fetch).mock.calls.length;act(()=>FakeWebSocket.instances[0]!.emit({eventId:'e9',schemaVersion:'1',eventType:'noop',timestamp:now,sequenceNumber:9,correlationId:'c',taskId:null,agentId:null,source:'test',payload:{}}));await waitFor(()=>expect(vi.mocked(fetch).mock.calls.length).toBeGreaterThan(before))})
})
