import { NavLink, Navigate, Route, Routes } from 'react-router-dom'
import { AgentDetails, TaskDetails } from './components/Details'
import { Status } from './components/Status'
import { useAppStore } from './state/AppStore'
import { Dashboard } from './pages/Dashboard';import { Tasks } from './pages/Tasks';import { Agents } from './pages/Agents';import { Approvals } from './pages/Approvals';import { Audit } from './pages/Audit';import { Office } from './pages/Office';import { System } from './pages/System'
const links: ReadonlyArray<readonly [string,string,string]>=[['/','Dashboard','⌂'],['/tasks','Tasks','✓'],['/agents','Agents','◆'],['/approvals','Approvals','◇'],['/audit','Audit','≡'],['/office','Office','▦'],['/system','System','⚙']]
export default function App(){const {loading,error,system,connection,notifications,action,selectedAgentId,selectedTaskId}=useAppStore();if(loading)return <main className="center-state" aria-live="polite"><div className="loader"/><h1>Synchronizing Jarvis</h1><p>Loading deterministic seed state…</p></main>
 return <div className="shell"><aside className="sidebar"><div className="brand"><span>J</span><div><strong>JARVIS</strong><small>Agent ecosystem</small></div></div><nav aria-label="Primary">{links.map(([to,label,icon])=><NavLink key={to} to={to} end={to==='/' }><span aria-hidden="true">{icon}</span>{label}</NavLink>)}</nav><div className="sidebar-foot"><span className="sim-badge">SIMULATED MODE</span><small>Phase 1 · Local foundation</small></div></aside>
 <div className="workspace"><header className="topbar"><div className="system-summary"><Status value={connection}/><span className="desktop-only">API {system?.apiSchemaVersion??'—'} · {system?.simulator.state??'offline'}</span>{error&&<span className="top-error">Last-known state</span>}</div><div className="top-actions"><span aria-label={`${notifications.filter(n=>!n.isRead).length} unread notifications`}>◉ <b>{notifications.filter(n=>!n.isRead).length}</b></span><button className="emergency" onClick={()=>void action(system?.emergencyStop?'/api/system/resume':'/api/system/emergency-stop')}>{system?.emergencyStop?'Resume system':'Emergency stop'}</button></div></header><main id="main-content" className="content" aria-live="polite"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/tasks" element={<Tasks/>}/><Route path="/agents" element={<Agents/>}/><Route path="/approvals" element={<Approvals/>}/><Route path="/audit" element={<Audit/>}/><Route path="/office" element={<Office/>}/><Route path="/system" element={<System/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></main>
 <nav className="mobile-nav" aria-label="Mobile primary">{links.slice(0,5).map(([to,label,icon])=><NavLink key={to} to={to} end={to==='/' }><span aria-hidden="true">{icon}</span><small>{label}</small></NavLink>)}</nav></div>{selectedAgentId&&<AgentDetails/>}{selectedTaskId&&<TaskDetails/>}</div>}
