import { Runtime } from './pages/Runtime'
import { BusinessLab } from './pages/BusinessLab'
import { lazy, Suspense, useLayoutEffect, useState } from 'react'
import { Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { AgentDetails, TaskDetails } from './components/Details'
import { Status } from './components/Status'
import { useAppStore } from './state/AppStore'
import { Dashboard } from './pages/Dashboard';import { Tasks } from './pages/Tasks';import { Agents } from './pages/Agents';import { Approvals } from './pages/Approvals';import { Audit } from './pages/Audit';import { System } from './pages/System'
const Office = lazy(() => import('./pages/Office').then(module => ({ default: module.Office })))
const links: ReadonlyArray<readonly [string,string,string]>=[['/','Dashboard','⌂'],['/tasks','Tasks','✓'],['/agents','Agents','◆'],['/approvals','Approvals','◇'],['/audit','Audit','≡'],['/runtime','Planning','◈'],['/lab','Business Lab','▤'],['/office','Office','▦'],['/system','System','⚙']]
const routeTitles:Record<string,string>={'/':'Dashboard','/tasks':'Tasks','/agents':'Agents','/approvals':'Approvals','/audit':'Audit','/runtime':'Planning','/lab':'Business Lab','/office':'Office','/system':'System'}
function RouteTitle(){const {pathname}=useLocation();useLayoutEffect(()=>{document.title=`${routeTitles[pathname]??'Not found'} · Jarvis`},[pathname]);return null}
function NotFound(){return <section className="empty"><h1>Page not found</h1><p>The requested Jarvis view does not exist.</p><Link className="primary" to="/">Return to dashboard</Link></section>}
export default function App(){const [controlError,setControlError]=useState('');const [controlBusy,setControlBusy]=useState(false);const {loading,error,system,connection,notifications,action,selectedAgentId,selectedTaskId}=useAppStore();if(loading)return <main className="center-state" aria-live="polite"><div className="loader"/><h1>Synchronizing Jarvis</h1><p>Loading deterministic seed state…</p></main>
 return <div className="shell"><aside className="sidebar"><div className="brand"><span>J</span><div><strong>JARVIS</strong><small>Agent ecosystem</small></div></div><nav aria-label="Primary">{links.map(([to,label,icon])=><NavLink key={to} to={to} end={to==='/' }><span aria-hidden="true">{icon}</span>{label}</NavLink>)}</nav><div className="sidebar-foot"><span className="sim-badge">LOCAL AI HUB</span><small>Simulation + opt-in local planning</small></div></aside>
 <div className="workspace"><RouteTitle/><header className="topbar"><div className="system-summary"><Status value={connection}/><span className="desktop-only">API {system?.apiSchemaVersion??'—'} · {system?.simulator.state??'offline'}</span>{error&&<span className="top-error">Last-known state</span>}</div><div className="top-actions"><span aria-label={`${notifications.filter(n=>!n.isRead).length} unread notifications`}>◉ <b>{notifications.filter(n=>!n.isRead).length}</b></span><button className="emergency" disabled={controlBusy} onClick={async()=>{setControlBusy(true);setControlError('');try{await action(system?.emergencyStop?'/api/system/resume':'/api/system/emergency-stop')}catch(error){setControlError(error instanceof Error?error.message:'System control failed')}finally{setControlBusy(false)}}}>{system?.emergencyStop?'Resume system':'Emergency stop'}</button></div></header><main id="main-content" className="content" aria-live="polite">{controlError&&<p role="alert">{controlError}</p>}<Routes><Route path="/" element={<Dashboard/>}/><Route path="/tasks" element={<Tasks/>}/><Route path="/agents" element={<Agents/>}/><Route path="/approvals" element={<Approvals/>}/><Route path="/audit" element={<Audit/>}/><Route path="/runtime" element={<Runtime/>}/><Route path="/lab" element={<BusinessLab/>}/><Route path="/office" element={<Suspense fallback={<p>Loading office…</p>}><Office/></Suspense>}/><Route path="/system" element={<System/>}/><Route path="*" element={<NotFound/>}/></Routes></main>
 <nav className="mobile-nav" aria-label="Mobile primary">{links.map(([to,label,icon])=><NavLink key={to} to={to} end={to==='/' }><span aria-hidden="true">{icon}</span><small>{label}</small></NavLink>)}</nav></div>{selectedAgentId&&<AgentDetails/>}{selectedTaskId&&<TaskDetails/>}</div>}
