import { useAppStore } from '../state/AppStore'
import { Progress, Status } from './Status'

export function AgentDetails(){const {agents,departments,tasks,selectedAgentId,selectAgent}=useAppStore();const agent=agents.find(a=>a.id===selectedAgentId);if(!agent)return null
  const manager=agents.find(a=>a.id===agent.managerId);const department=departments.find(d=>d.id===agent.departmentId);const task=tasks.find(t=>t.id===agent.currentTaskId)
  return <div className="drawer-backdrop" onClick={()=>selectAgent(null)}><section className="drawer" role="dialog" aria-modal="true" aria-labelledby="agent-title" onClick={e=>e.stopPropagation()}>
    <button className="icon-button close" onClick={()=>selectAgent(null)} aria-label="Close agent details">×</button><p className="eyebrow">{agent.isTemporary?'Temporary simulated agent':'Permanent simulated agent'}</p><h2 id="agent-title">{agent.name}</h2><p>{agent.role} · {department?.name}</p><Status value={agent.status}/><Progress value={agent.progress}/><p>{agent.description}</p>
    <dl className="details-grid"><div><dt>Manager</dt><dd>{manager?.name??'None'}</dd></div><div><dt>Current task</dt><dd>{task?.title??'None'}</dd></div><div><dt>Queue</dt><dd>{agent.queuedTaskIds.length}</dd></div><div><dt>Reliability</dt><dd>{Math.round(agent.performance.reliabilityScore*100)}%</dd></div><div><dt>Office</dt><dd>{agent.office.zone} · {agent.office.deskId}</dd></div><div><dt>Manifest</dt><dd>{agent.version}</dd></div><div><dt>Deployment</dt><dd>{agent.deploymentStatus}</dd></div><div><dt>Memory</dt><dd>Fixture-only placeholder</dd></div></dl>
    <h3>Goals</h3><ul>{agent.goals.map(x=><li key={x}>{x}</li>)}</ul><h3>Capabilities</h3><div className="chips">{agent.capabilities.map(x=><span key={x}>{x}</span>)}</div><h3>Tool policy</h3><p><strong>Allowed:</strong> {agent.allowedTools.join(', ')||'None'}</p><p><strong>Denied:</strong> {agent.deniedTools.join(', ')}</p><h3>Performance</h3><p>{Math.round(agent.performance.completionRate*100)}% completion · {Math.round(agent.performance.accuracyScore*100)}% accuracy · {agent.performance.failedTaskCount} failed task(s) · {agent.performance.userCorrectionCount} correction(s)</p>
  </section></div>}

export function TaskDetails(){const {tasks,agents,approvals,artifacts,auditEvents,selectedTaskId,selectTask}=useAppStore();const task=tasks.find(t=>t.id===selectedTaskId);if(!task)return null
  const children=tasks.filter(t=>t.parentTaskId===task.id);const timeline=auditEvents.filter(e=>e.taskId===task.id);return <div className="drawer-backdrop" onClick={()=>selectTask(null)}><section className="drawer" role="dialog" aria-modal="true" aria-labelledby="task-title" onClick={e=>e.stopPropagation()}>
    <button className="icon-button close" onClick={()=>selectTask(null)} aria-label="Close task details">×</button><p className="eyebrow">Task · {task.priority} priority</p><h2 id="task-title">{task.title}</h2><Status value={task.status}/><Progress value={task.progress}/><p><strong>Original request</strong><br/>{task.request}</p><p>{task.statusMessage}</p>
    <dl className="details-grid"><div><dt>Manager</dt><dd>{agents.find(a=>a.id===task.assignedManagerId)?.name??'Unassigned'}</dd></div><div><dt>Specialists</dt><dd>{task.assignedAgentIds.map(id=>agents.find(a=>a.id===id)?.name??id).join(', ')||'None'}</dd></div><div><dt>Retries</dt><dd>{task.retryCount} / {task.maxRetries}</dd></div><div><dt>Blockers</dt><dd>{task.blockedBy.join(', ')||'None'}</dd></div></dl>
    {task.error&&<div className="callout danger"><strong>{task.error.code}</strong><br/>{task.error.message}</div>}<h3>Child tasks</h3>{children.length?<ul>{children.map(c=><li key={c.id}><button className="link-button" onClick={()=>selectTask(c.id)}>{c.title} · {c.status}</button></li>)}</ul>:<p className="muted">No child tasks.</p>}
    <h3>Approvals</h3>{task.approvalIds.map(id=>{const a=approvals.find(x=>x.id===id);return a?<p key={id}>{a.title} · <Status value={a.status}/></p>:null})}<h3>Artifacts</h3>{task.artifactIds.map(id=>{const a=artifacts.find(x=>x.id===id);return a?<div className="artifact" key={id}><strong>{a.name}</strong><p>{a.summary}</p><code>{a.simulatedPath}</code></div>:null})}{!task.artifactIds.length&&<p className="muted">No artifacts yet.</p>}
    {task.result&&<><h3>Final result</h3><div className="callout success">{task.result}</div></>}<h3>Timeline</h3>{timeline.length?<ol className="timeline">{timeline.map(e=><li key={e.id}><time>{new Date(e.timestamp).toLocaleString()}</time><strong>{e.summary}</strong><small>Sequence {e.sequenceNumber} · {e.correlationId}</small></li>)}</ol>:<p className="muted">No task events yet.</p>}
  </section></div>}
