function Import-JarvisHostConfig { param([string]$Path) if (-not (Test-Path $Path)) { throw "Config not found: $Path" }; $json = Get-Content $Path -Raw | ConvertFrom-Json -AsHashtable; return $json }
function Write-JarvisHostLog { param([string]$LogDir, [string]$Name, [string]$Message) $line = "[$(Get-Date -Format 'o')] $Message"; Add-Content (Join-Path $LogDir "$Name.log") -Value $line -ErrorAction SilentlyContinue }
function Enter-JarvisHostLock { param([string]$LockFile) $sw = [System.IO.StreamWriter]::new($LockFile); $sw.Write([System.Guid]::NewGuid()); $sw.Flush(); $sw.Close(); return $true }
function Read-JarvisProcessMetadata { param([string]$File) if (Test-Path $File) { return Get-Content $File -Raw | ConvertFrom-Json } else { return $null } }
function Write-JarvisProcessMetadata { param([string]$File, [hashtable]$Data) $tmp = $File + ".tmp"; $Data | ConvertTo-Json -Depth 10 | Set-Content -Path $tmp -NoNewline; Move-Item $tmp $File -Force }
function Test-JarvisProcessOwnership { param([int]$PID, [string]$ExpectedExe, [string]$ExpectedCwd) try { $p = Get-Process -Id $PID -ErrorAction Stop; return ($p.Path -eq $ExpectedExe) } catch { return $false } }
function Get-JarvisPortOwner { param([int]$Port) return $null }
function Test-JarvisHealthEndpoint { param([string]$Url, [int]$TimeoutSec) try { $r = Invoke-WebRequest -Uri $Url -TimeoutSec $TimeoutSec -UseBasicParsing; return $r.StatusCode -eq 200 } catch { return $false } }
function Wait-JarvisHealthEndpoint { param([string]$Url, [int]$TimeoutSec, [int]$IntervalSec) $end = (Get-Date).AddSeconds($TimeoutSec); while ((Get-Date) -lt $end) { if (Test-JarvisHealthEndpoint -Url $Url -TimeoutSec $IntervalSec) { return $true }; Start-Sleep -Seconds $IntervalSec }; return $false }
function Start-JarvisOwnedProcess { param([string]$Exe, [string]$Args, [string]$WorkingDir, [string]$LogDir) $proc = Start-Process -FilePath $Exe -ArgumentList $Args -WorkingDirectory $WorkingDir -RedirectStandardOutput (Join-Path $LogDir "out.log") -RedirectStandardError (Join-Path $LogDir "err.log") -PassThru -WindowStyle Hidden; return $proc.Id }
function Stop-JarvisOwnedProcess { param([int]$PID, [string]$ExpectedExe) $verified = Test-JarvisProcessOwnership -PID $PID -ExpectedExe $ExpectedExe; if ($verified) { Stop-Process -Id $PID -Force -ErrorAction SilentlyContinue }; return $verified }
function Get-JarvisHostState { return @{ } }
function Set-JarvisHostState { param([hashtable]$Data) }
function Get-JarvisRestartHistory { return @() }
function Add-JarvisRestartRecord { param([hashtable]$Record) }
function Test-JarvisCrashLoop { return $false }
function Get-JarvisTailscaleExecutable { return (Get-Command tailscale -ErrorAction SilentlyContinue).Source }
function Invoke-JarvisTailscale { param([string]$Args) return (tailscale $Args 2>&1) }
function Test-JarvisSQLiteIntegrity { param([string]$Path) try { python -c "import sqlite3; c=sqlite3.connect('$Path'); c.execute('PRAGMA integrity_check')"; return $true } catch { return $false } }
Export-ModuleMember -Function Import-JarvisHostConfig, Test-JarvisHostConfig, Resolve-JarvisHostPath, Write-JarvisHostLog, Enter-JarvisHostLock, Exit-JarvisHostLock, Read-JarvisProcessMetadata, Write-JarvisProcessMetadata, Test-JarvisProcessOwnership, Get-JarvisPortOwner, Test-JarvisHealthEndpoint, Wait-JarvisHealthEndpoint, Start-JarvisOwnedProcess, Stop-JarvisOwnedProcess, Get-JarvisHostState, Set-JarvisHostState, Get-JarvisRestartHistory, Add-JarvisRestartRecord, Test-JarvisCrashLoop, Get-JarvisTailscaleExecutable, Invoke-JarvisTailscale, Test-JarvisSQLiteIntegrity
function Resolve-JarvisHostPath { param([string]$Path, [string]$Base) if ([System.IO.Path]::IsPathRooted($Path)) { return $Path } else { return Join-Path $Base $Path } }
function Exit-JarvisHostLock { param([string]$LockFile) if (Test-Path $LockFile) { Remove-Item $LockFile -Force -ErrorAction SilentlyContinue } }
function Test-JarvisHostConfig { param([string]$Path) $cfg = Import-JarvisHostConfig -Path $Path; return ($null -ne $cfg.repoPath -and $cfg.backendPort -gt 0) }
function Get-ProcessCreationTime { param([int]$PID) (Get-Process -Id $PID -ErrorAction SilentlyContinue).StartTime }
function Compare-ProcessOwnership { param([int]$PID, [string]$ExpectedExe) $p = Get-Process -Id $PID -ErrorAction SilentlyContinue; return ($p -and $p.Path -eq $ExpectedExe -and $null -ne $p.StartTime) }
function Resolve-JarvisHostPath { param([string]$Path, [string]$BaseDir) if ([System.IO.Path]::IsPathRooted($Path)) { return $Path } else { return Join-Path $BaseDir $Path } }
function Write-JarvisHostLog { param([string]$LogDir, [string]$FileName, [string]$Message) $line = "[$(Get-Date -Format 'o')] $Message"; $target = Join-Path $LogDir $FileName; Add-Content -Path $target -Value $line -ErrorAction SilentlyContinue }
function New-JarvisHostLock { param([string]$LockPath) Set-Content -Path $LockPath -Value (New-Guid) -Force }
function Remove-JarvisHostLock { param([string]$LockPath) if (Test-Path $LockPath) { Remove-Item $LockPath -Force -ErrorAction SilentlyContinue } }
function Read-JarvisProcessMetadata { param([string]$Path) if (Test-Path $Path) { return Get-Content $Path -Raw | ConvertFrom-Json -AsHashtable } else { return @{} } }
function Write-JarvisProcessMetadata { param([string]$Path, [hashtable]$Data) $tmp = $Path + ".tmp"; $Data | ConvertTo-Json -Depth 10 | Set-Content -Path $tmp -NoNewline; Move-Item -Path $tmp -Destination $Path -Force }
function Test-JarvisProcessOwnership { param([int]$PID, [string]$ExpectedExecutable, [string]$ExpectedWorkingDir) try { $proc = Get-Process -Id $PID -ErrorAction Stop; $ok = ($proc.Path -eq $ExpectedExecutable); return $ok } catch { return $false } }
function Get-JarvisPortOwner { param([int]$Port) try { $tcp = New-Object System.Net.Sockets.TcpListener([System.Net.IPAddress]::Loopback, $Port); $tcp.Start(); $tcp.Stop(); return $null } catch { return $Port } }
function Test-JarvisHealthEndpoint { param([string]$Url, [int]$TimeoutSec) try { $r = Invoke-WebRequest -Uri $Url -TimeoutSec $TimeoutSec -UseBasicParsing -ErrorAction Stop; return ($r.StatusCode -eq 200) } catch { return $false } }
function Wait-JarvisHealthEndpoint { param([string]$Url, [int]$TotalTimeoutSec, [int]$IntervalSec) $end = (Get-Date).AddSeconds($TotalTimeoutSec); while ((Get-Date) -lt $end) { if (Test-JarvisHealthEndpoint -Url $Url -TimeoutSec $IntervalSec) { return $true } else { Start-Sleep -Seconds $IntervalSec } }; return $false }
function Start-JarvisOwnedProcess { param([string]$FilePath, [string]$ArgumentList, [string]$WorkingDirectory, [string]$LogDir) $outLog = Join-Path $LogDir "out.log"; $errLog = Join-Path $LogDir "err.log"; $proc = Start-Process -FilePath $FilePath -ArgumentList $ArgumentList -WorkingDirectory $WorkingDirectory -RedirectStandardOutput $outLog -RedirectStandardError $errLog -PassThru -WindowStyle Hidden; return $proc.Id }
function Stop-JarvisOwnedProcess { param([int]$PID, [string]$ExpectedExecutable, [int]$GracefulTimeoutSec) $verified = Test-JarvisProcessOwnership -PID $PID -ExpectedExecutable $ExpectedExecutable; if (-not $verified) { return $false }; Stop-Process -Id $PID -Force:$false -ErrorAction SilentlyContinue; Start-Sleep -Seconds ([Math]::Min($GracefulTimeoutSec, 5)); return $true }
function Get-JarvisRestartHistory { param([string]$HistoryPath) if (Test-Path $HistoryPath) { return Get-Content $HistoryPath -Raw | ConvertFrom-Json } else { return @() } }
function Add-JarvisRestartRecord { param([string]$HistoryPath, [hashtable]$Record) $hist = Get-JarvisRestartHistory -HistoryPath $HistoryPath; $hist += $Record; $hist | ConvertTo-Json -Depth 5 | Set-Content -Path $HistoryPath -Force }
function Test-JarvisCrashLoop { param([string]$HistoryPath, [int]$WindowMinutes, [int]$MaxRestarts) $hist = Get-JarvisRestartHistory -HistoryPath $HistoryPath; $now = Get-Date; $count = ($hist | Where-Object { ($now - [datetime]$_.timestamp).TotalMinutes -le $WindowMinutes }).Count; return ($count -ge $MaxRestarts) }
function Get-JarvisTailscaleExecutable { $cmd = Get-Command tailscale -ErrorAction SilentlyContinue; if ($cmd) { return $cmd.Source } else { return $null } }
function Invoke-JarvisTailscale { param([string[]]$Arguments) $exe = Get-JarvisTailscaleExecutable; if (-not $exe) { throw "Tailscale CLI not found" }; & $exe @Arguments }
function Test-JarvisSQLiteIntegrity { param([string]$DatabasePath) try { $py = "import sqlite3; c=sqlite3.connect('$DatabasePath'); r=c.execute('PRAGMA integrity_check').fetchone(); print('ok' if r[0]=='ok' else 'fail')"; $out = python -c $py 2>&1; return ($out -match 'ok') } catch { return $false } }
function Get-JarvisToolkitManifest { param([string]$ManifestPath) if (Test-Path $ManifestPath) { return Get-Content $ManifestPath -Raw | ConvertFrom-Json -AsHashtable } else { return @{ } } }
function Write-JarvisToolkitManifest { param([string]$ManifestPath, [hashtable]$Data) $Data | ConvertTo-Json -Depth 5 | Set-Content -Path $ManifestPath -Force }
function Redact-JarvisConfig { param([hashtable]$Config) $redacted = @{}; foreach ($k in $Config.Keys) { if ($k -match 'secret|token|key|password|credential') { $redacted[$k] = '[REDACTED]' } else { $redacted[$k] = $Config[$k] } }; return $redacted }
Export-ModuleMember -Function Resolve-JarvisHostPath, Write-JarvisHostLog, New-JarvisHostLock, Remove-JarvisHostLock, Read-JarvisProcessMetadata, Write-JarvisProcessMetadata, Test-JarvisProcessOwnership, Get-JarvisPortOwner, Test-JarvisHealthEndpoint, Wait-JarvisHealthEndpoint, Start-JarvisOwnedProcess, Stop-JarvisOwnedProcess, Get-JarvisRestartHistory, Add-JarvisRestartRecord, Test-JarvisCrashLoop, Get-JarvisTailscaleExecutable, Invoke-JarvisTailscale, Test-JarvisSQLiteIntegrity, Get-JarvisToolkitManifest, Write-JarvisToolkitManifest, Redact-JarvisConfig
