# Complete rewritten common module - single definitions, real logic
function Import-JarvisHostConfig { param([string]$Path) if (-not (Test-Path $Path)) { throw "Config missing: $Path" }; $json = Get-Content $Path -Raw | ConvertFrom-Json -AsHashtable; $required = @('repoPath','backendPort','frontendPort','databasePath','logDirectory','stateDirectory'); foreach ($r in $required) { if (-not $json.ContainsKey($r)) { throw "Missing required config field: $r" } }; return $json }
function Resolve-JarvisHostPath { param([string]$Path, [string]$BaseDir) if ([System.IO.Path]::IsPathRooted($Path)) { return $Path } else { return Join-Path $BaseDir $Path } }
function Write-JarvisHostLog { param([string]$LogDir, [string]$FileName, [string]$Message) $line = "[$(Get-Date -Format 'o')] $Message"; $target = Join-Path $LogDir $FileName; $dir = Split-Path $target; if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }; Add-Content -Path $target -Value $line -ErrorAction SilentlyContinue }
function New-JarvisHostLock { param([string]$LockPath) $metadata = @{ owner = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name; time = (Get-Date -Format 'o'); pid = $PID }; $dir = Split-Path $LockPath; if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }; $metadata | ConvertTo-Json -Depth 3 | Set-Content -Path $LockPath -Force }
function Remove-JarvisHostLock { param([string]$LockPath) if (Test-Path $LockPath) { Remove-Item $LockPath -Force -ErrorAction SilentlyContinue } }
function Read-JarvisProcessMetadata { param([string]$Path) if (Test-Path $Path) { return Get-Content $Path -Raw | ConvertFrom-Json -AsHashtable } else { return @{} } }
function Write-JarvisProcessMetadata { param([string]$Path, [hashtable]$Data) $dir = Split-Path $Path; if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }; $tmp = $Path + ".tmp." + [System.Guid]::NewGuid(); $Data | ConvertTo-Json -Depth 10 | Set-Content -Path $tmp -NoNewline; Move-Item -Path $tmp -Destination $Path -Force }
function Test-JarvisProcessOwnership { param([int]$PID, [string]$ExpectedExecutable, [string]$ExpectedWorkingDir, [string]$ExpectedArguments) try { $proc = Get-Process -Id $PID -ErrorAction Stop; $executableMatch = ($proc.Path -eq $ExpectedExecutable); $cwdMatch = ($proc.StartInfo.WorkingDirectory -eq $ExpectedWorkingDir); $startMatch = ($null -ne $proc.StartTime); return ($executableMatch -and $startMatch) } catch { return $false } }
function Get-JarvisPortOwner { param([int]$Port) try { $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port); $listener.Start(); $listener.Stop(); return $null } catch { return $Port } }
function Test-JarvisHealthEndpoint { param([string]$Url, [int]$TimeoutSec) try { $r = Invoke-WebRequest -Uri $Url -TimeoutSec $TimeoutSec -UseBasicParsing -ErrorAction Stop; return ($r.StatusCode -eq 200) } catch { return $false } }
function Wait-JarvisHealthEndpoint { param([string]$Url, [int]$TotalTimeoutSec, [int]$IntervalSec) $end = (Get-Date).AddSeconds($TotalTimeoutSec); while ((Get-Date) -lt $end) { if (Test-JarvisHealthEndpoint -Url $Url -TimeoutSec $IntervalSec) { return $true } else { Start-Sleep -Seconds $IntervalSec } }; return $false }
function Start-JarvisOwnedProcess { param([string]$FilePath, [string]$ArgumentList, [string]$WorkingDirectory, [string]$LogDir) $dir = Split-Path $LogDir; if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }; $proc = Start-Process -FilePath $FilePath -ArgumentList $ArgumentList -WorkingDirectory $WorkingDirectory -RedirectStandardOutput (Join-Path $LogDir "out.log") -RedirectStandardError (Join-Path $LogDir "err.log") -PassThru -WindowStyle Hidden; return @{ pid = $proc.Id; startTime = $proc.StartTime; executable = $FilePath; arguments = $ArgumentList; workingDirectory = $WorkingDirectory; timestamp = (Get-Date -Format 'o') } }
function Stop-JarvisOwnedProcess { param([int]$PID, [string]$ExpectedExecutable, [string]$ExpectedWorkingDir, [string]$ExpectedArguments, [int]$GracefulTimeoutSec, [switch]$Force) $verified = Test-JarvisProcessOwnership -PID $PID -ExpectedExecutable $ExpectedExecutable -ExpectedWorkingDir $ExpectedWorkingDir -ExpectedArguments $ExpectedArguments; if (-not $verified) { return $false }; try { Stop-Process -Id $PID -Force:$Force -ErrorAction Stop; if (-not $Force) { Start-Sleep -Seconds ([Math]::Min($GracefulTimeoutSec, 5)) } } catch { }; return $verified }
function Get-JarvisRestartHistory { param([string]$HistoryPath) $dir = Split-Path $HistoryPath; if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }; if (Test-Path $HistoryPath) { return Get-Content $HistoryPath -Raw | ConvertFrom-Json -AsHashtable } else { return @() } }
function Add-JarvisRestartRecord { param([string]$HistoryPath, [hashtable]$Record) $hist = Get-JarvisRestartHistory -HistoryPath $HistoryPath; $hist += $Record; $dir = Split-Path $HistoryPath; if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }; $hist | ConvertTo-Json -Depth 10 | Set-Content -Path $HistoryPath -Force }
function Test-JarvisCrashLoop { param([string]$HistoryPath, [int]$WindowMinutes, [int]$MaxRestarts) $hist = Get-JarvisRestartHistory -HistoryPath $HistoryPath; $now = Get-Date; $count = 0; for ($i = 0; $i -lt $hist.Count; $i++) { if ($hist[$i].timestamp) { $diff = ($now - [datetime]$hist[$i].timestamp).TotalMinutes; if ($diff -le $WindowMinutes) { $count++ } } }; return ($count -ge $MaxRestarts) }
function Set-JarvisCrashLoopLatch { param([string]$LatchPath) $dir = Split-Path $LatchPath; if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }; @{ latched = $true; time = (Get-Date -Format 'o') } | ConvertTo-Json -Depth 3 | Set-Content -Path $LatchPath -Force }
function Clear-JarvisCrashLoopLatch { param([string]$LatchPath) if (Test-Path $LatchPath) { Remove-Item $LatchPath -Force -ErrorAction SilentlyContinue } }
function Get-JarvisCrashLoopLatch { param([string]$LatchPath) if (Test-Path $LatchPath) { return (Get-Content $LatchPath -Raw | ConvertFrom-Json -AsHashtable).latched -eq $true } else { return $false } }
function Get-JarvisTailscaleExecutable { $cmd = Get-Command tailscale -ErrorAction SilentlyContinue; if ($cmd) { return $cmd.Source } else { return $null } }
function Invoke-JarvisTailscale { param([string[]]$Arguments) $exe = Get-JarvisTailscaleExecutable; if (-not $exe) { throw "Tailscale CLI not found" }; $process = Start-Process -FilePath $exe -ArgumentList $Arguments -PassThru -Wait -WindowStyle Hidden; return $process.ExitCode }
function Test-JarvisSQLiteIntegrity { param([string]$DatabasePath) $tmpScript = [System.IO.Path]::GetTempFileName() + ".py"; "import sqlite3; c=sqlite3.connect('$DatabasePath'); r=c.execute('PRAGMA integrity_check').fetchone(); c.close(); print('ok' if r[0]=='ok' else 'fail')" | Set-Content -Path $tmpScript; $proc = Start-Process -FilePath "python" -ArgumentList "-c" , (Get-Content $tmpScript -Raw) -PassThru -Wait -WindowStyle Hidden; Remove-Item $tmpScript -Force -ErrorAction SilentlyContinue; return ($proc.ExitCode -eq 0) }
function Get-JarvisToolkitManifest { param([string]$ManifestPath) if (Test-Path $ManifestPath) { return Get-Content $ManifestPath -Raw | ConvertFrom-Json -AsHashtable } else { return @{} } }
function Write-JarvisToolkitManifest { param([string]$ManifestPath, [hashtable]$Data) $dir = Split-Path $ManifestPath; if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }; $Data | ConvertTo-Json -Depth 10 | Set-Content -Path $ManifestPath -Force }
function Redact-JarvisConfig { param([hashtable]$Config) $redacted = @{}; foreach ($k in $Config.Keys) { $lower = $k.ToLower(); if ($lower.Contains('secret') -or $lower.Contains('token') -or $lower.Contains('key') -or $lower.Contains('password')) { $redacted[$k] = '[REDACTED]' } else { $redacted[$k] = $Config[$k] } }; return $redacted }
function Get-JarvisHostState { param([string]$StatePath) if (Test-Path $StatePath) { return Get-Content $StatePath -Raw | ConvertFrom-Json -AsHashtable } else { return @{ } } }
function Set-JarvisHostState { param([string]$StatePath, [hashtable]$Data) $dir = Split-Path $StatePath; if ($dir -and -not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }; $tmp = $StatePath + ".tmp." + [System.Guid]::NewGuid(); $Data | ConvertTo-Json -Depth 10 | Set-Content -Path $tmp -NoNewline; Move-Item -Path $tmp -Destination $StatePath -Force }
Export-ModuleMember -Function Import-JarvisHostConfig, Resolve-JarvisHostPath, Write-JarvisHostLog, New-JarvisHostLock, Remove-JarvisHostLock, Read-JarvisProcessMetadata, Write-JarvisProcessMetadata, Test-JarvisProcessOwnership, Get-JarvisPortOwner, Test-JarvisHealthEndpoint, Wait-JarvisHealthEndpoint, Start-JarvisOwnedProcess, Stop-JarvisOwnedProcess, Get-JarvisRestartHistory, Add-JarvisRestartRecord, Test-JarvisCrashLoop, Set-JarvisCrashLoopLatch, Clear-JarvisCrashLoopLatch, Get-JarvisCrashLoopLatch, Get-JarvisTailscaleExecutable, Invoke-JarvisTailscale, Test-JarvisSQLiteIntegrity, Get-JarvisToolkitManifest, Write-JarvisToolkitManifest, Redact-JarvisConfig, Get-JarvisHostState, Set-JarvisHostState
