"""agent identity rbac foundation

Revision ID: a87a487dd714
Revises: 20260724_03
Create Date: 2026-07-27 02:51:35.892963
"""

import sqlalchemy as sa
from alembic import op

revision = "a87a487dd714"
down_revision = "20260724_03"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identity_capabilities",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("stable_key", sa.String(length=120), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stable_key"),
    )
    op.create_table(
        "identity_permissions",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("stable_key", sa.String(length=120), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.String(length=60), nullable=False),
        sa.Column("action", sa.String(length=60), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("resource_type", "action"),
    )
    with op.batch_alter_table("identity_permissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_permissions_stable_key"), ["stable_key"], unique=True
        )

    op.create_table(
        "identity_ranks",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("stable_key", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority_level", sa.Integer(), nullable=False),
        sa.Column("hierarchy_level", sa.Integer(), nullable=False),
        sa.Column("delegation_ceiling", sa.Integer(), nullable=True),
        sa.Column("approval_ceiling", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("hierarchy_level >= 0"),
        sa.CheckConstraint("priority_level >= 0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hierarchy_level"),
        sa.UniqueConstraint("priority_level"),
        sa.UniqueConstraint("stable_key"),
    )
    op.create_table(
        "identity_roles",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("stable_key", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("role_scope", sa.String(length=30), nullable=False),
        sa.Column("is_system_role", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stable_key"),
    )
    op.create_table(
        "identity_seat_priority_policies",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.String(length=120), nullable=False),
        sa.Column("subject_type", sa.String(length=20), nullable=False),
        sa.Column("subject_id", sa.String(length=80), nullable=False),
        sa.Column("priority_marker", sa.String(length=20), nullable=False),
        sa.Column("reservation_state", sa.String(length=20), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("identity_seat_priority_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_seat_priority_policies_resource_id"),
            ["resource_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_identity_seat_priority_policies_subject_id"),
            ["subject_id"],
            unique=False,
        )

    op.create_table(
        "identity_teams",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("stable_key", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("team_type", sa.String(length=40), nullable=False),
        sa.Column("lifecycle_state", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stable_key"),
    )
    op.create_table(
        "identity_agents",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("stable_key", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("agent_type", sa.String(length=30), nullable=False),
        sa.Column("lifecycle_state", sa.String(length=30), nullable=False),
        sa.Column("operational_status", sa.String(length=30), nullable=False),
        sa.Column("rank_id", sa.String(length=80), nullable=True),
        sa.Column("is_system_agent", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["rank_id"],
            ["identity_ranks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("identity_agents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_agents_agent_type"), ["agent_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_identity_agents_lifecycle_state"), ["lifecycle_state"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_identity_agents_operational_status"),
            ["operational_status"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_identity_agents_rank_id"), ["rank_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_identity_agents_stable_key"), ["stable_key"], unique=True
        )

    op.create_table(
        "identity_role_permissions",
        sa.Column("role_id", sa.String(length=80), nullable=False),
        sa.Column("permission_id", sa.String(length=80), nullable=False),
        sa.Column("effect", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("effect IN ('allow','deny')"),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["identity_permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["identity_roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "identity_agent_capabilities",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("agent_id", sa.String(length=80), nullable=False),
        sa.Column("capability_id", sa.String(length=80), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_by", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["identity_capabilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "capability_id", "starts_at"),
    )
    with op.batch_alter_table("identity_agent_capabilities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_agent_capabilities_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_identity_agent_capabilities_capability_id"),
            ["capability_id"],
            unique=False,
        )

    op.create_table(
        "identity_agent_permissions",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("agent_id", sa.String(length=80), nullable=False),
        sa.Column("permission_id", sa.String(length=80), nullable=False),
        sa.Column("effect", sa.String(length=10), nullable=False),
        sa.Column("resource_type", sa.String(length=60), nullable=True),
        sa.Column("resource_id", sa.String(length=120), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_by", sa.String(length=80), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("effect IN ('allow','deny')"),
        sa.CheckConstraint(
            "(resource_type IS NULL AND resource_id IS NULL) OR "
            "(resource_type IS NOT NULL AND resource_id IS NOT NULL)",
            name="ck_identity_agent_permissions_resource_scope",
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["identity_permissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agent_id",
            "permission_id",
            "effect",
            "resource_type",
            "resource_id",
            "starts_at",
        ),
    )
    with op.batch_alter_table("identity_agent_permissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_agent_permissions_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_identity_agent_permissions_permission_id"),
            ["permission_id"],
            unique=False,
        )
        batch_op.create_index(
            "uq_identity_agent_permissions_global",
            ["agent_id", "permission_id", "effect", "starts_at"],
            unique=True,
            sqlite_where=sa.text("resource_type IS NULL AND resource_id IS NULL"),
            postgresql_where=sa.text("resource_type IS NULL AND resource_id IS NULL"),
        )

    op.create_table(
        "identity_agent_roles",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("agent_id", sa.String(length=80), nullable=False),
        sa.Column("role_id", sa.String(length=80), nullable=False),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_id", sa.String(length=120), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_by", sa.String(length=80), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["identity_roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id", "role_id", "scope_type", "scope_id", "starts_at"),
    )
    with op.batch_alter_table("identity_agent_roles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_agent_roles_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_identity_agent_roles_role_id"), ["role_id"], unique=False
        )
        batch_op.create_index(
            "uq_identity_agent_roles_global",
            ["agent_id", "role_id", "scope_type", "starts_at"],
            unique=True,
            sqlite_where=sa.text("scope_type = 'global' AND scope_id IS NULL"),
            postgresql_where=sa.text("scope_type = 'global' AND scope_id IS NULL"),
        )

    op.create_table(
        "identity_approval_authority_policies",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("agent_id", sa.String(length=80), nullable=False),
        sa.Column("may_request_approval", sa.Boolean(), nullable=False),
        sa.Column("may_grant_approval", sa.Boolean(), nullable=False),
        sa.Column("maximum_risk_level", sa.String(length=20), nullable=True),
        sa.Column("maximum_cost_usd", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("action_category", sa.String(length=80), nullable=False),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_id", sa.String(length=120), nullable=True),
        sa.Column("effect", sa.String(length=10), nullable=False),
        sa.Column("allow_self_approval", sa.Boolean(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("effect IN ('allow','deny')"),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["identity_agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("identity_approval_authority_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_approval_authority_policies_action_category"),
            ["action_category"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_identity_approval_authority_policies_agent_id"),
            ["agent_id"],
            unique=False,
        )

    op.create_table(
        "identity_audit_events",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("actor_agent_id", sa.String(length=80), nullable=True),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_id", sa.String(length=80), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_agent_id"],
            ["identity_agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("identity_audit_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_audit_events_actor_agent_id"), ["actor_agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_identity_audit_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_identity_audit_events_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_identity_audit_events_target_type"), ["target_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_identity_audit_events_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "identity_delegation_policies",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("delegator_agent_id", sa.String(length=80), nullable=False),
        sa.Column("target_agent_id", sa.String(length=80), nullable=True),
        sa.Column("task_category", sa.String(length=80), nullable=False),
        sa.Column("required_capability_id", sa.String(length=80), nullable=True),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_id", sa.String(length=120), nullable=True),
        sa.Column("maximum_target_rank", sa.Integer(), nullable=True),
        sa.Column("maximum_delegation_depth", sa.Integer(), nullable=False),
        sa.Column("effect", sa.String(length=10), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("assigned_by", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("effect IN ('allow','deny')"),
        sa.CheckConstraint("maximum_delegation_depth >= 0"),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["delegator_agent_id"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["required_capability_id"],
            ["identity_capabilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_agent_id"],
            ["identity_agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("identity_delegation_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_delegation_policies_delegator_agent_id"),
            ["delegator_agent_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_identity_delegation_policies_target_agent_id"),
            ["target_agent_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_identity_delegation_policies_task_category"),
            ["task_category"],
            unique=False,
        )

    op.create_table(
        "identity_resource_access_policies",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("subject_type", sa.String(length=20), nullable=False),
        sa.Column("subject_id", sa.String(length=80), nullable=True),
        sa.Column("resource_type", sa.String(length=40), nullable=False),
        sa.Column("resource_id", sa.String(length=120), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("effect", sa.String(length=10), nullable=False),
        sa.Column("access_state", sa.String(length=20), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_by", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("effect IN ('allow','deny')"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["identity_agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("identity_resource_access_policies", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_resource_access_policies_resource_id"),
            ["resource_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_identity_resource_access_policies_resource_type"),
            ["resource_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_identity_resource_access_policies_subject_id"),
            ["subject_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_identity_resource_access_policies_subject_type"),
            ["subject_type"],
            unique=False,
        )

    op.create_table(
        "identity_supervisor_relationships",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("supervisor_agent_id", sa.String(length=80), nullable=False),
        sa.Column("subordinate_agent_id", sa.String(length=80), nullable=False),
        sa.Column("relationship_type", sa.String(length=20), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_by", sa.String(length=80), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("supervisor_agent_id <> subordinate_agent_id"),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subordinate_agent_id"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supervisor_agent_id"],
            ["identity_agents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("identity_supervisor_relationships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_supervisor_relationships_subordinate_agent_id"),
            ["subordinate_agent_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_identity_supervisor_relationships_supervisor_agent_id"),
            ["supervisor_agent_id"],
            unique=False,
        )

    op.create_table(
        "identity_team_memberships",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("team_id", sa.String(length=80), nullable=False),
        sa.Column("agent_id", sa.String(length=80), nullable=False),
        sa.Column("membership_role", sa.String(length=20), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_by", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["identity_agents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["identity_teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "agent_id", "starts_at"),
    )
    with op.batch_alter_table("identity_team_memberships", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_team_memberships_agent_id"), ["agent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_identity_team_memberships_team_id"), ["team_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("identity_team_memberships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identity_team_memberships_team_id"))
        batch_op.drop_index(batch_op.f("ix_identity_team_memberships_agent_id"))

    op.drop_table("identity_team_memberships")
    with op.batch_alter_table("identity_supervisor_relationships", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identity_supervisor_relationships_supervisor_agent_id"))
        batch_op.drop_index(batch_op.f("ix_identity_supervisor_relationships_subordinate_agent_id"))

    op.drop_table("identity_supervisor_relationships")
    with op.batch_alter_table("identity_resource_access_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identity_resource_access_policies_subject_type"))
        batch_op.drop_index(batch_op.f("ix_identity_resource_access_policies_subject_id"))
        batch_op.drop_index(batch_op.f("ix_identity_resource_access_policies_resource_type"))
        batch_op.drop_index(batch_op.f("ix_identity_resource_access_policies_resource_id"))

    op.drop_table("identity_resource_access_policies")
    with op.batch_alter_table("identity_delegation_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identity_delegation_policies_task_category"))
        batch_op.drop_index(batch_op.f("ix_identity_delegation_policies_target_agent_id"))
        batch_op.drop_index(batch_op.f("ix_identity_delegation_policies_delegator_agent_id"))

    op.drop_table("identity_delegation_policies")
    with op.batch_alter_table("identity_audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identity_audit_events_timestamp"))
        batch_op.drop_index(batch_op.f("ix_identity_audit_events_target_type"))
        batch_op.drop_index(batch_op.f("ix_identity_audit_events_target_id"))
        batch_op.drop_index(batch_op.f("ix_identity_audit_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_identity_audit_events_actor_agent_id"))

    op.drop_table("identity_audit_events")
    with op.batch_alter_table("identity_approval_authority_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identity_approval_authority_policies_agent_id"))
        batch_op.drop_index(batch_op.f("ix_identity_approval_authority_policies_action_category"))

    op.drop_table("identity_approval_authority_policies")
    with op.batch_alter_table("identity_agent_roles", schema=None) as batch_op:
        batch_op.drop_index("uq_identity_agent_roles_global")
        batch_op.drop_index(batch_op.f("ix_identity_agent_roles_role_id"))
        batch_op.drop_index(batch_op.f("ix_identity_agent_roles_agent_id"))

    op.drop_table("identity_agent_roles")
    with op.batch_alter_table("identity_agent_permissions", schema=None) as batch_op:
        batch_op.drop_index("uq_identity_agent_permissions_global")
        batch_op.drop_index(batch_op.f("ix_identity_agent_permissions_permission_id"))
        batch_op.drop_index(batch_op.f("ix_identity_agent_permissions_agent_id"))

    op.drop_table("identity_agent_permissions")
    with op.batch_alter_table("identity_agent_capabilities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identity_agent_capabilities_capability_id"))
        batch_op.drop_index(batch_op.f("ix_identity_agent_capabilities_agent_id"))

    op.drop_table("identity_agent_capabilities")
    op.drop_table("identity_role_permissions")
    with op.batch_alter_table("identity_agents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identity_agents_stable_key"))
        batch_op.drop_index(batch_op.f("ix_identity_agents_rank_id"))
        batch_op.drop_index(batch_op.f("ix_identity_agents_operational_status"))
        batch_op.drop_index(batch_op.f("ix_identity_agents_lifecycle_state"))
        batch_op.drop_index(batch_op.f("ix_identity_agents_agent_type"))

    op.drop_table("identity_agents")
    op.drop_table("identity_teams")
    with op.batch_alter_table("identity_seat_priority_policies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identity_seat_priority_policies_subject_id"))
        batch_op.drop_index(batch_op.f("ix_identity_seat_priority_policies_resource_id"))

    op.drop_table("identity_seat_priority_policies")
    op.drop_table("identity_roles")
    op.drop_table("identity_ranks")
    with op.batch_alter_table("identity_permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identity_permissions_stable_key"))

    op.drop_table("identity_permissions")
    op.drop_table("identity_capabilities")
    # ### end Alembic commands ###
