/* Real API + worker fixture + original office assets. Uses the isolated smoke harness. */
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { chromium } = require(path.join(process.env.SMOKE_WEB, 'node_modules/playwright'))
const output = process.env.SMOKE_ARTIFACT_DIR
const base = process.env.SMOKE_BASE
const actor = process.env.SMOKE_ACTOR

;(async () => {
  fs.mkdirSync(output, { recursive: true })
  const browser = await chromium.launch({ headless: true })
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  page.setDefaultTimeout(15000)
  const errors = [], failures = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  page.on('response', response => { if (response.status() >= 400) failures.push(`${response.status()} ${response.url()}`) })
  const api = async (method, url, data) => {
    const response = await page.request.fetch(`${base}${url}`, { method, data })
    assert.ok(response.ok(), `${method} ${url}: ${await response.text()}`)
    return (await response.json()).data
  }
  const changeIdentity = async id => page.getByLabel('Office identity').selectOption(id)
  const waitPlacement = async (id, state) => page.waitForFunction(({ id, state }) => document.querySelector(`[data-testid="office-agent-${id}"]`)?.getAttribute('data-movement') === state, { id, state })
  try {
    const second = await api('POST', '/api/identity/agents', { stable_key: 'office-browser-companion', display_name: 'Office companion', agent_type: 'worker' })
    await api('POST', `/api/identity/agents/${second.id}/activate`)
    await page.goto(`${process.env.SMOKE_UI}/office`)
    await page.getByRole('heading', { name: 'Operations floor' }).waitFor()
    await page.waitForFunction(() => document.querySelector('.office-background')?.naturalWidth === 8192)
    await changeIdentity(actor)
    await page.getByLabel('Assign desk').selectOption('POSITION_022')
    await page.getByRole('button', { name: 'Assign identity', exact: true }).click()
    await waitPlacement(actor, 'idle')
    await changeIdentity(second.id)
    await page.getByLabel('Assign desk').selectOption('POSITION_030')
    await page.getByLabel('Original sprite').selectOption('agent-sheet-06')
    await page.getByRole('button', { name: 'Assign identity', exact: true }).click()
    await waitPlacement(second.id, 'idle')
    await page.getByRole('button', { name: 'Focus identity', exact: true }).click()
    await page.screenshot({ path: path.join(output, 'office-two-identities.png'), fullPage: true })
    assert.equal(await page.locator('.live-office-agent').count(), 2)
    assert.equal(await page.getByRole('button', { name: 'Stop movement', exact: true }).isEnabled(), false)
    await changeIdentity(actor)
    await page.getByLabel('Move destination').selectOption('POSITION_028')
    await page.getByRole('button', { name: 'Move identity', exact: true }).click()
    await waitPlacement(actor, 'moving')
    const movingPoint = await page.getByTestId(`office-agent-${actor}`).getAttribute('data-x')
    await page.waitForFunction(({ id, x }) => document.querySelector(`[data-testid="office-agent-${id}"]`)?.getAttribute('data-x') !== x, { id: actor, x: movingPoint })
    await page.getByRole('button', { name: 'Stop movement', exact: true }).click()
    await waitPlacement(actor, 'stopped')
    const stopped = await api('GET', '/api/office')
    const stoppedPlacement = stopped.placements.find(item => item.identityId === actor)
    assert.ok(stoppedPlacement.motion.stoppedAt)
    await page.screenshot({ path: path.join(output, 'office-stopped-route.png'), fullPage: true })
    await page.reload()
    await waitPlacement(actor, 'stopped')
    await changeIdentity(actor)
    const refreshed = await api('GET', '/api/office')
    assert.deepEqual(refreshed.placements.find(item => item.identityId === actor).position, stoppedPlacement.position)
    await page.getByRole('button', { name: 'Continue move', exact: true }).click()
    await waitPlacement(actor, 'idle')
    const arrived = await api('GET', '/api/office')
    assert.equal(arrived.placements.find(item => item.identityId === actor).stationId, 'POSITION_028')
    console.log('Office assignments, stop/reload/continue, and arrival verified')
    // Run a real worker execution through the existing task/planning UI.
    const nav = page.getByRole('navigation', { name: 'Primary', exact: true })
    await nav.getByRole('link', { name: 'Tasks', exact: true }).click()
    await page.getByRole('button', { name: '+ New task' }).click()
    await page.getByLabel('Title', { exact: true }).fill('Office observed planning')
    await page.getByLabel('Description', { exact: true }).fill('Verify office activity from real persisted worker execution.')
    const created = page.waitForResponse(response => response.url().endsWith('/api/tasks') && response.request().method() === 'POST')
    await page.getByRole('button', { name: 'Create task', exact: true }).click()
    const task = (await (await created).json()).data
    await nav.getByRole('link', { name: 'Planning', exact: true }).click()
    await page.getByLabel('Task and history').selectOption(task.id)
    await page.getByRole('button', { name: 'Prepare local planner for this task', exact: true }).click()
    await page.getByText('Local planner prepared for this task. Queue the plan when ready.', { exact: true }).waitFor()
    await page.getByRole('button', { name: 'Queue local plan', exact: true }).click()
    await nav.getByRole('link', { name: 'Office', exact: true }).click()
    await changeIdentity(actor)
    await page.getByRole('button', { name: 'Focus identity', exact: true }).click()
    await page.getByTestId(`office-agent-${actor}`).filter({ hasText: 'working' }).waitFor()
    await page.screenshot({ path: path.join(output, 'office-real-worker-activity.png'), fullPage: true })
    await page.getByTestId(`office-agent-${actor}`).filter({ hasText: 'completed' }).waitFor({ timeout: 30000 })
    console.log('Office actual worker activity and completion verified')
    // Emergency stop freezes movement and requires an explicit continuation.
    await page.getByRole('button', { name: 'Move identity', exact: true }).click()
    await waitPlacement(actor, 'moving')
    await page.getByRole('button', { name: 'Emergency stop', exact: true }).click()
    await waitPlacement(actor, 'stopped')
    console.log('Office emergency stop persisted')
    await page.getByText('Emergency stop is active.', { exact: false }).waitFor()
    assert.equal(await page.getByRole('button', { name: 'Continue move', exact: true }).isEnabled(), false)
    await page.getByRole('button', { name: 'Resume system', exact: true }).click()
    await page.getByRole('button', { name: 'Continue move', exact: true }).click()
    await waitPlacement(actor, 'idle')
    await changeIdentity(second.id)
    await page.getByRole('button', { name: 'Release desk assignment', exact: true }).click()
    await page.getByTestId(`office-agent-${second.id}`).waitFor({ state: 'detached' })
    assert.notEqual(await page.getByLabel('Assign desk').inputValue(), 'POSITION_022', 'Reassignment must not default to another identity\'s occupied desk')
    assert.equal(await page.getByLabel('Assign desk').locator('option[value="POSITION_022"]').evaluate(option => option.disabled), true)
    await page.getByLabel('Assign desk').selectOption('POSITION_030')
    await page.getByRole('button', { name: 'Assign identity', exact: true }).click()
    await waitPlacement(second.id, 'idle')
    await page.setViewportSize({ width: 390, height: 844 })
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.getByRole('button', { name: 'Fit office', exact: true }).click()
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'Mobile overflow')
    await page.screenshot({ path: path.join(output, 'office-live-mobile.png'), fullPage: true })
    assert.deepEqual(errors, [])
    assert.deepEqual(failures, [])
    const final = await api('GET', '/api/office')
    fs.writeFileSync(path.join(output, 'office-browser-evidence.json'), JSON.stringify({ catalog: final.catalog.version, identityCount: final.placements.length, assertions: ['two original sprites', 'UI assignments', 'explicit collision-validated move', 'stop', 'refresh reconstruction', 'continued arrival', 'actual worker activity', 'emergency stop', 'release and reassign', 'mobile layout'], taskId: task.id }, null, 2))
    console.log('PASS: live office placements, original sprites, movement/stop/refresh/occupancy, real worker activity, emergency stop, mobile layout')
  } catch (error) {
    await page.screenshot({ path: path.join(output, 'failure.png'), fullPage: true }).catch(() => {})
    console.error({ errors, failures })
    console.error(await api('GET', '/api/office').catch(failure => String(failure)))
    throw error
  } finally { await browser.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
