from __future__ import annotations

from copy import deepcopy
from datetime import UTC, datetime, timedelta
from typing import Any

NOW = datetime(2026, 1, 15, 14, 0, tzinfo=UTC)


def _performance(reliability: float) -> dict[str, Any]:
    return {
        "completionRate": 0.94,
        "accuracyScore": 0.92,
        "averageCompletionTime": 420,
        "failedTaskCount": 1,
        "userCorrectionCount": 2,
        "reviewerScore": 0.93,
        "reliabilityScore": reliability,
    }


def _agent(
    agent_id: str,
    name: str,
    role: str,
    department: str,
    manager: str | None,
    zone: str,
    desk: str,
    x: int,
    y: int,
    capabilities: list[str],
) -> dict[str, Any]:
    return {
        "id": agent_id,
        "name": name,
        "role": role,
        "description": {
            "jarvis": "Receives requests, plans work, delegates, monitors, and presents outcomes.",
            "atlas": "Breaks research projects into subtasks and combines findings.",
            "scout": "Conducts simulated research and produces structured findings.",
            "archive": "Organizes simulated files and retrieves preference documents.",
            "sentinel": "Reviews results for unsupported claims and unsafe actions.",
        }[agent_id],
        "goals": ["Deliver transparent simulated work", "Preserve approval and audit boundaries"],
        "departmentId": department,
        "managerId": manager,
        "status": "idle",
        "currentTaskId": None,
        "queuedTaskIds": [],
        "progress": 0,
        "statusMessage": "Available",
        "capabilities": capabilities,
        "allowedTools": ["simulated_workspace", "simulated_research"],
        "deniedTools": ["shell", "external_email", "financial_accounts"],
        "approvalPolicy": {"requiresApprovalFor": ["external_action", "high_risk"]},
        "memoryAccess": {"scope": "seed-fixtures-only", "durable": False},
        "performance": _performance(0.97 if agent_id == "jarvis" else 0.93),
        "resourceProfile": {"heavyTasks": 1, "lightweightTasks": 3, "simulated": True},
        "office": {
            "zone": zone,
            "deskId": desk,
            "spriteIdentifier": f"sprite-{agent_id}",
            "displayPosition": {"x": x, "y": y},
            "currentAnimationState": "idle",
        },
        "createdAt": NOW,
        "updatedAt": NOW,
        "version": "1.0.0",
        "deploymentStatus": "simulated",
        "isTemporary": False,
    }


def build_seed() -> dict[str, list[dict[str, Any]]]:
    agents = [
        _agent(
            "jarvis",
            "Jarvis",
            "Executive Manager",
            "executive",
            None,
            "Executive",
            "E-01",
            50,
            10,
            ["planning", "delegation", "synthesis"],
        ),
        _agent(
            "atlas",
            "Atlas",
            "Research Manager",
            "research",
            "jarvis",
            "Research",
            "R-01",
            25,
            35,
            ["research_planning", "review", "synthesis"],
        ),
        _agent(
            "scout",
            "Scout",
            "Research Specialist",
            "research",
            "atlas",
            "Research",
            "R-02",
            35,
            50,
            ["simulated_research", "citation_review"],
        ),
        _agent(
            "archive",
            "Archive",
            "File and Document Specialist",
            "operations",
            "jarvis",
            "Personal Operations",
            "P-01",
            65,
            45,
            ["simulated_retrieval", "artifact_organization"],
        ),
        _agent(
            "sentinel",
            "Sentinel",
            "Security Reviewer",
            "governance",
            "jarvis",
            "Governance",
            "G-01",
            78,
            30,
            ["claim_review", "risk_review"],
        ),
    ]
    tasks = [
        {
            "id": "task-completed",
            "title": "Organize reading list",
            "description": "Simulated organization of a reading list.",
            "request": "Organize my reading list",
            "createdBy": "local-user",
            "assignedManagerId": "jarvis",
            "assignedAgentIds": ["archive"],
            "priority": "low",
            "status": "completed",
            "progress": 100,
            "statusMessage": "Delivered",
            "artifactIds": ["artifact-reading-list"],
            "result": "A categorized simulated reading list was prepared.",
            "createdAt": NOW - timedelta(days=2),
            "startedAt": NOW - timedelta(days=2),
            "updatedAt": NOW - timedelta(days=2),
            "completedAt": NOW - timedelta(days=2),
        },
        {
            "id": "task-demo",
            "title": "Seven-day Caribbean trip recommendation",
            "description": "Research and prepare a seven-day Caribbean trip recommendation based on travel preferences.",
            "request": "Research and prepare a seven-day Caribbean trip recommendation based on the user's travel preferences, organize the findings, review the result, and deliver a final report.",
            "createdBy": "local-user",
            "assignedManagerId": "jarvis",
            "assignedAgentIds": [],
            "priority": "high",
            "status": "in_progress",
            "progress": 5,
            "statusMessage": "Active demonstration staged at its deterministic checkpoint",
            "approvalIds": ["approval-pending"],
            "createdAt": NOW - timedelta(hours=2),
            "updatedAt": NOW - timedelta(hours=2),
        },
        {
            "id": "task-queued",
            "title": "Summarize household manual",
            "description": "Prepare a simulated summary after the trip workflow.",
            "request": "Summarize the fixture manual",
            "createdBy": "local-user",
            "assignedManagerId": "jarvis",
            "assignedAgentIds": ["archive"],
            "priority": "medium",
            "status": "queued",
            "progress": 0,
            "statusMessage": "Queued behind demo",
            "createdAt": NOW - timedelta(hours=1),
            "updatedAt": NOW - timedelta(hours=1),
        },
        {
            "id": "task-failed",
            "title": "Research discontinued route",
            "description": "A seeded controlled failure.",
            "request": "Research a discontinued route",
            "createdBy": "local-user",
            "assignedManagerId": "atlas",
            "assignedAgentIds": ["scout"],
            "priority": "medium",
            "status": "failed",
            "progress": 35,
            "statusMessage": "Simulated source unavailable",
            "error": {
                "code": "SIMULATED_SOURCE_UNAVAILABLE",
                "message": "Fixture source is unavailable.",
            },
            "retryCount": 0,
            "createdAt": NOW - timedelta(days=1),
            "startedAt": NOW - timedelta(days=1),
            "updatedAt": NOW - timedelta(days=1),
        },
    ]
    approvals = [
        {
            "id": "approval-pending",
            "taskId": "task-demo",
            "requestedByAgentId": "scout",
            "actionType": "simulated_report_publish",
            "title": "Publish revised trip report",
            "description": "Approve publishing inside the simulated workspace only.",
            "reason": "Human review gate demonstration",
            "riskLevel": "yellow",
            "affectedResources": ["simulated://workspace/travel"],
            "exactActionPreview": "Save the final recommendation to the simulated artifact list.",
            "expectedOutcome": "A report artifact appears in the task.",
            "reversalMethod": "Remove the simulated artifact after reset.",
            "expiresAt": NOW + timedelta(days=5000),
            "status": "pending",
            "createdAt": NOW - timedelta(minutes=20),
        },
        {
            "id": "approval-expired",
            "taskId": "task-failed",
            "requestedByAgentId": "scout",
            "actionType": "simulated_source_access",
            "title": "Access expired fixture",
            "description": "An intentionally expired approval.",
            "reason": "Failure scenario",
            "riskLevel": "orange",
            "affectedResources": ["simulated://expired"],
            "exactActionPreview": "Read an expired fixture.",
            "expectedOutcome": "No action occurs.",
            "reversalMethod": "No action required.",
            "expiresAt": NOW - timedelta(days=1),
            "status": "expired",
            "createdAt": NOW - timedelta(days=2),
        },
        {
            "id": "approval-black",
            "taskId": "task-failed",
            "requestedByAgentId": "sentinel",
            "actionType": "prohibited_external_action",
            "title": "Prohibited external action",
            "description": "Demonstrates a black-risk action that can never be approved.",
            "reason": "Policy boundary test",
            "riskLevel": "black",
            "affectedResources": ["external://prohibited"],
            "exactActionPreview": "No execution is implemented.",
            "expectedOutcome": "Approval is refused.",
            "reversalMethod": "Not applicable.",
            "expiresAt": NOW + timedelta(days=5000),
            "status": "pending",
            "createdAt": NOW,
        },
    ]
    return deepcopy(
        {
            "departments": [
                {
                    "id": "executive",
                    "name": "Executive",
                    "description": "Coordination and delivery",
                    "managerAgentId": "jarvis",
                    "agentIds": ["jarvis"],
                },
                {
                    "id": "research",
                    "name": "Research and Knowledge",
                    "description": "Simulated research",
                    "managerAgentId": "atlas",
                    "agentIds": ["atlas", "scout"],
                },
                {
                    "id": "operations",
                    "name": "Personal Operations",
                    "description": "Simulated document operations",
                    "managerAgentId": "jarvis",
                    "agentIds": ["archive"],
                },
                {
                    "id": "governance",
                    "name": "Governance",
                    "description": "Safety and review",
                    "managerAgentId": "jarvis",
                    "agentIds": ["sentinel"],
                },
            ],
            "agents": agents,
            "tasks": tasks,
            "approvals": approvals,
            "artifacts": [
                {
                    "id": "artifact-reading-list",
                    "taskId": "task-completed",
                    "name": "Reading list.md",
                    "type": "report",
                    "summary": "A simulated categorized reading list.",
                    "simulatedPath": "simulated://workspace/reading-list.md",
                    "createdAt": NOW - timedelta(days=2),
                }
            ],
            "notifications": [
                {
                    "id": "notification-1",
                    "title": "Welcome to simulated mode",
                    "message": "No real agents or integrations are connected.",
                    "level": "info",
                    "isRead": False,
                    "createdAt": NOW,
                }
            ],
            "audit": [
                {
                    "id": "audit-1",
                    "timestamp": NOW - timedelta(days=2),
                    "eventType": "task.completed",
                    "actorAgentId": "jarvis",
                    "taskId": "task-completed",
                    "previousState": "in_progress",
                    "newState": "completed",
                    "summary": "Seeded task completed in simulation.",
                    "correlationId": "seed",
                    "sequenceNumber": 1,
                    "payload": {"simulated": True},
                    "artifactIds": ["artifact-reading-list"],
                }
            ],
        }
    )
