import { useAppStore } from '../state/AppStore'
import { Status } from '../components/Status'
export function Dashboard(){const {system,tasks,agents,approvals,auditEvents,connection}=useAppStore();const active=tasks.filter(t=>!['queued','completed','cancelled','failed'].includes(t.status));const busy=agents.filter(a=>a.status!=='idle'&&a.status!=='offline');return <div>
  <header className="page-title"><div><p className="eyebrow">Command overview</p><h1>Good evening, operator.</h1><p>Everything shown here is deterministic simulation data.</p></div><div className="hero-orbit" aria-hidden="true"><span>J</span></div></header>
  <section className="metrics" aria-label="System metrics">{[
    ['Active tasks',active.length,'Work in motion'],['Queued',tasks.filter(t=>t.status==='queued').length,'Awaiting assignment'],['Approvals',approvals.filter(a=>a.status==='pending').length,'Human decisions'],['Available agents',agents.filter(a=>a.status==='idle').length,'Ready now'],['Busy agents',busy.length,'Currently active'],['Failed',agents.filter(a=>a.status==='failed').length,'Need attention']
  ].map(([label,value,note])=><article className="metric" key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section>
  <div className="split"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">Live operations</p><h2>System pulse</h2></div><Status value={system?.emergencyStop?'paused':system?.status??'loading'}/></div><div className="resource-grid">{system?.resources.map(r=><div key={r.name}><span>{r.name}</span><strong>{r.value}</strong><small>{r.label}</small></div>)}</div><p className="muted">WebSocket <Status value={connection}/> · simulator <Status value={system?.simulator.state??'loading'}/></p></section>
  <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Recent history</p><h2>Audit stream</h2></div></div><ol className="compact-timeline">{auditEvents.slice(-6).reverse().map(e=><li key={e.id}><span className="event-dot"/><div><strong>{e.summary}</strong><small>{new Date(e.timestamp).toLocaleTimeString()} · #{e.sequenceNumber}</small></div></li>)}</ol></section></div>
  <section className="panel"><div className="panel-heading"><div><p className="eyebrow">Organization</p><h2>Agent availability</h2></div></div><div className="agent-strip">{agents.map(a=><div key={a.id}><span className="avatar">{a.name[0]}</span><strong>{a.name}</strong><Status value={a.status}/></div>)}</div></section>
  </div>}
